/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.util.ArrayList;
import java.util.List;
import org.testng.annotations.*;

public class BrowserTest {

    @Test
    public void Execution() {
        List<String> result = new ArrayList();
        result = MakeDate("2018-01-02", 4);
        System.out.println(result);
        result = MakeDate("2018-12-27", 4);
        System.out.println(result);
        result = MakeDate("2018-06-14", 34);
        System.out.println(result);
    }

    public List<String> MakeDate(String Date, int count) {
        List<String> test = new ArrayList();
        int year = Integer.parseInt(Date.substring(0, 4));
        int month = Integer.parseInt(Date.substring(5, 7));
        int day = Integer.parseInt(Date.substring(8, 10));
        if ((day <= 0) || (day > 28) || (month <= 0) || (month > 12) || (count < 0)) return test;
        for (int i = 1; i <= count; i++) {
            if (day == 1) {
                if (month == 1) {
                    year--;
                    month = 12;
                } else month--;
                day = 28;
            } else day--;
        }
        test.add(BuildData(year, month, day));
        for (int i = 1; i <= (2*count); i++) {
            if (day == 28) {
                if (month == 12) {
                    year++;
                    month = 1;
                } else month++;
                day = 1;
            } else day++;
            test.add(BuildData(year, month, day));
        }
        return test;
    }

    public String BuildData(int year, int month, int day) {
        if ((month < 10) && (day < 10)) return (String.valueOf(year) + "-0" + String.valueOf(month) + "-0" + String.valueOf(day));
        if (month < 10) return (String.valueOf(year) + "-0" + String.valueOf(month) + "-" + String.valueOf(day));
        if (day < 10) return (String.valueOf(year) + "-" + String.valueOf(month) + "-0" + String.valueOf(day));
        return (String.valueOf(year) + "-" + String.valueOf(month) + "-" + String.valueOf(day));
    }
}